title: "[Bug] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve ELF! Please fill out the details below.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the issue clearly
      placeholder: When I run X, Y happens instead of Z
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we see this bug?
      placeholder: |
        1. Run `check in`
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should happen?
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: claude-code-version
    attributes:
      label: Claude Code version
      description: Run `claude --version`
      placeholder: "2.0.65"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/errors
      description: Paste any error messages
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight checklist
      options:
        - label: I searched existing discussions for this issue
          required: true
        - label: I'm using the latest version of ELF
          required: true
