title: "[Idea] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Got an idea to make ELF better? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Why do you need this feature?
      placeholder: Currently I have to... but it would be better if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should it work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other ways to solve this?

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight checklist
      options:
        - label: I searched existing discussions for similar ideas
          required: true
