name: Bug Report
description: Report a bug in the Emergent Learning Framework. Please search existing issues first!
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before You Submit

        **Please search existing issues first!** Your bug may already be reported.

        This template is for **confirmed bugs with reproducible steps**.
        If you're unsure whether something is a bug, please ask in [Discussions](https://github.com/TrueBurn/elf-framework/discussions) first.

        ---

  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and this bug has not been reported
          required: true
        - label: I have checked the Discussions to see if this is a known issue or question
          required: true
        - label: I can reproduce this bug with the steps provided below
          required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (Fedora/RHEL)
        - Linux (Arch)
        - Linux (Other)
        - WSL (Windows Subsystem for Linux)
    validations:
      required: true

  - type: dropdown
    id: shell
    attributes:
      label: Shell Environment
      description: What shell are you using?
      options:
        - PowerShell
        - CMD (Command Prompt)
        - Bash
        - Zsh
        - Fish
        - Git Bash / MSYS2
        - Other
    validations:
      required: true

  - type: input
    id: claude-version
    attributes:
      label: Claude Code Version
      description: "Run `claude --version` to get this"
      placeholder: "e.g., 2.0.65"
    validations:
      required: true

  - type: input
    id: elf-version
    attributes:
      label: ELF Version / Commit
      description: "Run `git rev-parse --short HEAD` in your ELF directory, or provide the version"
      placeholder: "e.g., aad6fd7 or v1.2.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: |
        A clear and detailed description of the bug.
        - What were you trying to do?
        - What actually happened?
        - When did this start happening?
      placeholder: |
        Describe the bug in detail. The more context you provide, the faster we can help.

        Minimum ~50 words recommended for useful bug reports.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: |
        Exact steps to reproduce the behavior. Be specific!
        We need to be able to follow these steps and see the same bug.
      placeholder: |
        1. Start Claude Code in directory '...'
        2. Run command '...'
        3. See error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected vs Actual Behavior
      description: What did you expect to happen? What actually happened?
      placeholder: |
        Expected: The query should return recent heuristics
        Actual: Got error "database is locked" and no output
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Screenshots
      description: |
        Paste any relevant log output, error messages, or screenshots.
        Use code blocks (```) for logs. Drag and drop images.
      placeholder: |
        ```
        Paste logs here
        ```
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context that might help (related issues, recent changes, workarounds tried, etc.)
    validations:
      required: false
